#!/usr/bin/env bash
#set -x

# /usr/bin/env Rscript --no-save

rscript=$(dirname $(readlink -f $0))"/PCA_3D.R"
function print_usage(){
 printf "
3D_PCA_run [OPTIONS] Directory
	-d | --dir	DESeq2 output directory
	-f | --factors	Factors for 3D PCA (e.g. factor1,factor2,factor3; Default = All factors)
	-l | --list	List all available factors for a specific analysis
	-r | --rscript	Path to PCA_3D.R (Defaults bash script directory)
	-h | --help	Display help
	
"
}

for arg in "$@"
do
 case $arg in
  -d | --dir)
  shift
  wd=$1
  shift
  ;;
  -f | --factors)
  shift
  factors=$1
  shift
  ;;
  -l | --list)
  list=1
  shift
  ;;
  -r | --rscript)
  shift
  rscript=$1
  shift
  ;;
  -h | --help)
  print_usage
  exit 1
  ;;
  *)
 esac
done
# xvfb-run 3D_PCA_run --factor factor --wd working_dir (includes PCA_data.RData)

if ! command -v xvfb-run &> /dev/null
then
 echo "xvfb not installed!"
 echo "Install using:"
 echo "sudo apt install xvfb"
 exit 1
fi

if [ ! -z ${list+x} ]
then
 Rscript $rscript --wd $wd --list
 exit 0
fi

if [ ${#factors[@]} -ne 0 ]
then
 xvfb-run $rscript --factors $factor --wd $wd
else
 xvfb-run $rscript --wd $wd
fi
