#!/usr/bin/env Rscript

if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}

packages_file = dirname(system(command = paste0("readlink -f ",gsub(pattern = "--file=",replacement ="",
                                                        grep(pattern = "--file",value = TRUE,commandArgs())),sep = ""),
                   intern = TRUE))
packages = read.table(file = normalizePath(paste0(packages_file,"/Rupdate.pkgs")))[[1]]

if(any(!packages %in% unique(rownames(installed.packages())))){
cat("Installing missing R packages...\n")
invisible(
  suppressMessages(
    sapply(packages[!packages %in% "bcbioRNASeq"],FUN = function(x) {
       if(!x %in% unique(rownames(installed.packages()))){
         cat("Installing package: ",x,"\n",sep = "")
         BiocManager::install(x,update = FALSE,ask = FALSE)
       }
    })))

if(!"bcbioRNASeq" %in% unique(rownames(installed.packages()))){
 install.packages(
    pkgs = "bcbioRNASeq",
    repos = c(
      "https://r.acidgenomics.com",
      BiocManager::repositories()
    ),
    dependencies = TRUE
  )
}
}

cat("Updating R packages...\n")
BiocManager::install(update = TRUE,ask = FALSE)
