#!/usr/bin/env Rscript

if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}


file_path = paste0(dirname(gsub(pattern = "--file=",replacement = "",grep(pattern = "--file",x = commandArgs(),value = TRUE))),"/Rupdate.pkgs")

if(file.exists(file_path)){
 cat("Getting previous packages from ",paste0(file_path),"...\n",sep = "")
 packages = unique(c(rownames(installed.packages()),read.table(file = file_path)[[1]]))
}else{
 packages = unique(rownames(installed.packages()))
}

if(any(!packages %in% unique(rownames(installed.packages())))){
cat("Installing missing R packages...\n")
invisible(
  suppressMessages(
    sapply(packages[!packages %in% "bcbioRNASeq"],FUN = function(x) {
       if(!x %in% unique(rownames(installed.packages()))){
         cat("Installing package: ",x,"\n",sep = "")
         BiocManager::install(x,update = FALSE,ask = FALSE)
       }
    })))

if(!"bcbioRNASeq" %in% unique(rownames(installed.packages()))){
 install.packages(
    pkgs = "bcbioRNASeq",
    repos = c(
      "https://r.acidgenomics.com",
      BiocManager::repositories()
    ),
    dependencies = TRUE
  )
}
}

cat("Writting package list to ",file_path,"...\n",sep = "")
write.table(file = file_path ,x = packages, row.names = FALSE, quote = FALSE, col.names=FALSE)

cat("Updating R packages...\n")
BiocManager::install(update = TRUE,ask = FALSE)
